### ISSUE TITLE
Blöde Frage

### ISSUE THREAD

**Issue by SISSI-S** [AlexBischof/buchungstool#10]
Huhu Alex,
ich glaub, ich steh auf dem Schlauch: wo kann man in dem neuen Buchungstool eigentlich das sehen, was in dem "alten" Buchungstool Usus war, also: welcher Tag ist wie belegt, wo haben wir eine Unter- bzw. Überbelegung (und Vorschläge, wie man diese revidieren kann)? 
Oder ist das einfach noch nicht drinnen?
Sorry, ist mir gerade so als Gedanke gekommen...
Grüße!

**Comment by AlexBischof** [comment]
Hi,
ist aktuell nicht drin und wir hatten es erstmal nach hinten geschoben. Können wir mit hoher Priorität nach unserem nächsten Treffen angehen, ok?

**Comment by SISSI-S** [comment]
Alles klar - ich war etwas verwirrt. Apropos nächstes Treffen: bei uns gab es Terminverschiebungen und Du wirst leider wieder nur mit mir alleine Vorlieb nehmen müssen, ok (ich bespreche mich natürlich mit Mirjam davor und bin dann unser gemeinsames Sprachrohr)?
