### ISSUE TITLE
Link zu Präsentation und Wiedersehen

### ISSUE THREAD

**Issue by SISSI-S** [AlexBischof/buchungstool#6]
Lieber Alex,
uns öffnen sich unter dem von Dir angegeben Link  (https://github.com/AlexBischof/buchungstool/blob/master/presentation/slides/20150930_V2/index.html) 
interessante Hieroglyphen. Sie sind sehr schön anzusehen, aber wir verstehen nüüüxxx ;-).
Gibt es für uns die Übersetzung in Bildchen bzw. schickst Du uns den richtigen Link dahin?
Was hältst Du vom 20.10. um 12:30h als Datum für ein weiteres Treffen?
Es grüßen die SISSIS

**Comment by AlexBischof** [comment]
Ich lasse euch die Präsentation anders zukommen. Termin passt.
